[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
test-gol ="test -- --nocapture"
serveur = "run --target wasm32-unknown-unknown"
build-wasm = "build --release --target wasm32-unknown-unknown"
lint = "clippy --all -- -W clippy::all -W clippy::pedantic -W clippy::restriction -W clippy::nursery -D warnings"
